Remove long options - they don't work and it is not worth making work

diff --git a/gh-mini-arc b/gh-mini-arc
--- a/gh-mini-arc
+++ b/gh-mini-arc
@@ -5,51 +5,41 @@ REPO_OWNER="$(gh api user --jq '.login')"
 template_repo="BagToad/mini-arc-template"
 REPO_NAME="fast-arc-$(date +%s)"
 
-while getopts ":s:t:n:h-:" opt; do
-  case ${opt} in
-    s)
-      grep -E '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$' <<< "${OPTARG}"  > /dev/null 2>&1 || { echo "Invalid scaleset name: ${OPTARG}"; exit 1; }
-      
-      if [ -z "${scalesets}" ]; then
-        scalesets="${OPTARG}"
-      else 
-        scalesets="${scalesets}:${OPTARG}"
-      fi
+while getopts ":s:t:n:h" opt; do
+    case ${opt} in
+        s)
+            grep -E '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$' <<< "${OPTARG}"  > /dev/null 2>&1 || { echo "Invalid scaleset name: ${OPTARG}"; exit 1; }
+            
+            if [ -z "${scalesets}" ]; then
+                scalesets="${OPTARG}"
+            else 
+                scalesets="${scalesets}:${OPTARG}"
+            fi
 
-      # echo "scalesets: ${scalesets}"
-      ;;
-    t)
-      template_repo=$OPTARG
-      ;;
-    n)
-      REPO_NAME=$OPTARG
-      ;;
-    h)
-      echo "Usage: $0 [options]"
-      echo "  -s, --scaleset <scaleset>  The scalesets to create secrets for"
-      echo "  -t, --template <template>  The template repo to use"
-      echo "  -n, --name <name>  The name for the new repository"
-      exit 0
-      ;;
-    -)
-      case "${OPTARG}" in
-        long-option)
-          long_option="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
-          ;;
-        *)
-          echo "Invalid option: --${OPTARG}" >&2
-          exit 1
-          ;;
-      esac;;
-    \?)
-      echo "Invalid option: -${OPTARG}" >&2
-      exit 1
-      ;;
-    :)
-      echo "Option -${OPTARG} requires an argument." >&2
-      exit 1
-      ;;
-  esac
+            # echo "scalesets: ${scalesets}"
+            ;;
+        t)
+            template_repo=$OPTARG
+            ;;
+        n)
+            REPO_NAME=$OPTARG
+            ;;
+        h)
+            echo "Usage: $0 [options]"
+            echo "  -s <scaleset>  The scalesets to create secrets for"
+            echo "  -t <template>  The template repo to use"
+            echo "  -n <name>  The name for the new repository"
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -${OPTARG}" >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -${OPTARG} requires an argument." >&2
+            exit 1
+            ;;
+    esac
 done
 
 if [ -z "${scalesets}" ]; then
